# Generated by Django 2.2.1 on 2019-05-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20190510_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='duration',
        ),
        migrations.AlterField(
            model_name='track',
            name='video_url',
            field=models.CharField(max_length=100, null=True, verbose_name='YouTube video URL'),
        ),
        migrations.AlterField(
            model_name='track',
            name='work_time',
            field=models.DurationField(null=True, verbose_name='Work time'),
        ),
    ]
