# Generated by Django 2.2.1 on 2019-05-10 19:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20190510_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='work_time',
        ),
        migrations.AddField(
            model_name='collection',
            name='playlist_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='YouTube playlist URL'),
        ),
        migrations.AddField(
            model_name='collection',
            name='work_time',
            field=models.DurationField(blank=True, null=True, verbose_name='Work time'),
        ),
        migrations.AddField(
            model_name='track',
            name='goodness',
            field=models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)], verbose_name='Goodness /20'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='cover_color',
            field=models.CharField(choices=[('D', 'Dark'), ('L', 'Light')], max_length=5, verbose_name="Cover art's color dominant"),
        ),
        migrations.AlterField(
            model_name='track',
            name='video_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='YouTube video URL'),
        ),
    ]
