# Generated by Django 2.2.1 on 2019-05-12 05:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20190510_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='track_number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Track number'),
        ),
    ]
