# Generated by Django 2.2.2 on 2019-06-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20190514_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='kind',
            field=models.CharField(choices=[('EP', 'EP'), ('SG', 'single'), ('AB', 'album')], max_length=6, verbose_name='Kind/type'),
        ),
    ]
