# Generated by Django 2.2.2 on 2019-06-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20190624_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='description',
        ),
        migrations.AddField(
            model_name='collection',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description (en)'),
        ),
        migrations.AddField(
            model_name='collection',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Description (fr)'),
        ),
    ]
