# Generated by Django 2.2.2 on 2019-06-24 14:16

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_auto_20190624_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='cover_accent_color',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name="Cover art's accent color"),
        ),
        migrations.AlterField(
            model_name='collection',
            name='cover_color',
            field=models.CharField(choices=[('D', 'Dark'), ('L', 'Light')], max_length=5, verbose_name="Cover art's color dominant (dark or light)"),
        ),
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.CharField(default='Mx3', max_length=50, verbose_name='Artis markupt'),
        ),
    ]
