# Generated by Django 2.2.2 on 2019-06-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_auto_20190624_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.CharField(default='Mx3', max_length=50, verbose_name='Artist'),
        ),
    ]
