# Generated by Django 2.2.2 on 2019-06-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_auto_20190624_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='cover_accent_color',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name="Cover art's accent color"),
        ),
    ]
