# Generated by Django 2.2.2 on 2019-06-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_auto_20190624_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='length',
            field=models.DurationField(null=True, verbose_name='Track duration'),
        ),
    ]
