# Generated by Django 2.2.2 on 2019-06-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_track_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='length',
            field=models.DurationField(blank=True, null=True, verbose_name='Track duration'),
        ),
    ]
