# Generated by Django 2.2.2 on 2019-06-28 13:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_auto_20190625_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='track_number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Track number'),
        ),
    ]
