# Generated by Django 2.2.1 on 2019-05-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.CharField(max_length=50, verbose_name='IP Adress')),
            ],
            options={
                'verbose_name': 'connection',
                'verbose_name_plural': 'connections',
            },
        ),
    ]
