# Generated by Django 2.2.2 on 2019-06-26 10:34

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='title slug')),
                ('length', models.DurationField(blank=True, null=True, verbose_name='Duration')),
                ('kind', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date published')),
                ('description_fr', models.TextField(blank=True, null=True, verbose_name='Description (fr)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description (en)')),
                ('downloads', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Downloads count')),
                ('likes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Likes count')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'videos',
            },
        ),
    ]
